#!/bin/bash

echo "------ System Information ------"

echo "Hostname:"
hostname

echo "Current User:"
whoami

echo "Date and Time:"
date

echo "System Uptime:"
uptime

echo "Operating System Information:"
uname -a

echo "Disk Usage:"
df -h

echo "Memory Usage:"
free -h
